#! /bin/sh

$HOME/.config/polybar/launch.sh
dunst &

wm-restack = bspwm
bspc rule -a Plank layer=below manage=off border=off
XDG_SESSION_TYPE=X11
plank &



pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width         1
bspc config window_gap          4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config normal_border_color "#FFFFFF"
bspc config active_border_color "#3F8BF6"
bspc config focused_border_color "#3F8BF6"
bspc config presel_feedback_color "#3F8BF6"
